# Generated by Django 4.2.2 on 2023-06-08 11:27

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Анастасия', 'Анастасия'), ('Ассоль', 'Ассоль'), ('Дримстар', 'Дримстар')], max_length=250, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Модельная линейка',
                'verbose_name_plural': 'Модельные линейки',
            },
        ),
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование продукции')),
                ('instruction', models.FileField(blank=True, upload_to=products.models.get_upload_path, verbose_name='Инструкция')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.сategories')),
                ('model_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.model_line')),
            ],
        ),
    ]
