# Generated by Django 4.2.2 on 2023-06-13 19:20

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Анастасия', 'Анастасия'), ('Ассоль', 'Ассоль'), ('Дримстар', 'Дримстар')], max_length=250, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Модельная линейка',
                'verbose_name_plural': 'Модельные линейки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование продукции')),
                ('instruction', models.FileField(blank=True, upload_to=products.models.get_upload_path, verbose_name='Инструкция')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product_on_partner_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Залит на сайт')),
                ('link', models.CharField(blank=True, max_length=250, verbose_name='ссылка на продукт у партнера')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_status', to='partners.partner', verbose_name='Партнер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_status', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукция у партнера',
                'verbose_name_plural': 'Продукция у партнера',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.сategories'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.model_line'),
        ),
    ]
