# Generated by Django 4.2.2 on 2023-06-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.сategories', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.model_line', verbose_name='Модельная линейка'),
        ),
    ]
