# Generated by Django 4.2.2 on 2023-06-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
