# Generated by Django 4.2.2 on 2023-06-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
        ('products', '0002_alter_product_options_product_on_partner_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_on_partner_status',
            options={'verbose_name': 'Продукция у партнера', 'verbose_name_plural': 'Продукция у партнера'},
        ),
        migrations.AddField(
            model_name='product_on_partner_status',
            name='link',
            field=models.CharField(blank=True, max_length=250, verbose_name='ссылка на продукт у партнера'),
        ),
        migrations.AlterField(
            model_name='product_on_partner_status',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='product_on_partner_status',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
    ]
