# Generated by Django 4.2.2 on 2023-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_main_category_alter_product_model_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_line',
            name='name',
            field=models.CharField(choices=[('Ассоль', 'Ассоль'), ('Агата', 'Агата'), ('Анастасия', 'Анастасия'), ('Виктория', 'Виктория'), ('Дримстар', 'Дримстар'), ('Изабель', 'Изабель'), ('Ирма', 'Ирма'), ('Монблан', 'Монблан'), ('Офис', 'Офис'), ('Скайлайт', 'Скайлайт'), ('Соня Премиум', 'Соня Премиум'), ('Элизабет', 'Элизабет'), ('Эмилия', 'Эмилия')], max_length=250, unique=True, verbose_name='Наименование категории'),
        ),
    ]
