# Generated by Django 4.2.2 on 2023-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Артикул сайта'),
        ),
    ]
