# Generated by Django 4.2.2 on 2023-06-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
        ('products', '0003_alter_product_on_partner_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_on_partner_status',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners.partner', verbose_name='Партнер'),
        ),
    ]
