# Generated by Django 4.2.2 on 2023-06-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_model_line_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product_on_partner_status',
            constraint=models.UniqueConstraint(fields=('product', 'partner'), name='unique_product_status'),
        ),
    ]
