# Generated by Django 4.2.2 on 2023-06-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_on_partner_status_partner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product_on_partner_status',
            name='unique_product_status',
        ),
    ]
