# Generated by Django 4.2.2 on 2023-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_on_partner_status_unique_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_count',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество упаковок'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_demensions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Габариты упаковок'),
        ),
    ]
