# Generated by Django 4.2.2 on 2023-07-12 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_packaging_count_product_packaging_demensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=datetime.date(2023, 7, 12), verbose_name='дата')),
                ('have_not_packeges_demensions_count', models.PositiveSmallIntegerField(verbose_name='не заполнено кол-во упаковок')),
                ('have_not_packeges_count', models.PositiveSmallIntegerField(verbose_name='не заполнено размеров упаковок')),
                ('have_not_weight_count', models.PositiveSmallIntegerField(verbose_name='не заполнено вес')),
                ('have_not_width_count', models.PositiveSmallIntegerField(verbose_name='не заполнено ширина')),
                ('have_not_height_count', models.PositiveSmallIntegerField(verbose_name='не заполнено высота')),
                ('have_not_depth_count', models.PositiveSmallIntegerField(verbose_name='не заполнено глубина')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
