# Generated by Django 4.2.2 on 2023-07-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
        ('products', '0007_progress_alter_product_url'),
    ]

    operations = [
    ]
