# Generated by Django 4.2.2 on 2023-07-18 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230718_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.date(2023, 7, 18), verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='have_not_packeges_demensions_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено кол-во упаковок'),
        ),
    ]
