# Generated by Django 4.2.2 on 2023-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_progress_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='have_not_packeges_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено размеров упаковок'),
        ),
    ]
