# Generated by Django 4.2.2 on 2023-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_progress_have_not_packeges_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='have_not_depth_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено глубина'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='have_not_height_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено высота'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='have_not_weight_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено вес'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='have_not_width_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='не заполнено ширина'),
        ),
    ]
