# Generated by Django 4.2.2 on 2023-07-20 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_progress_have_not_depth_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_on_partner_status',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена у партнера'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.date(2023, 7, 20), verbose_name='дата'),
        ),
    ]
