# Generated by Django 4.2.2 on 2023-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название партнера')),
                ('full_name_official', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Ссылка на сайт партнера')),
                ('site', models.CharField(max_length=100, unique=True, verbose_name='Ссылка на сайт партнера')),
                ('manager', models.CharField(blank=True, max_length=250, verbose_name='ФИО менеджера')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Телефон менеджера')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Емейл менеджера')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('partnership_shema', models.CharField(blank=True, help_text='Например: агентская схема, предоплата, скидка 30%', max_length=250, verbose_name='Модель сотрудничества')),
            ],
        ),
    ]
