# Generated by Django 4.2.2 on 2023-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_name_official',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Полное название организации'),
        ),
    ]
